---
title: "Masters Research"
output: html_notebook
---

this gets participant information, #, condition, date and file name
```{r}
source('~/Desktop/grad/ImplicitProcesses/implicitprocesses/preprocessing.R')
newdata <- getpinfo()
newdata1 <- getpangles(cond = 0)#this is now you combine data for each condition and trialtype
combinetrials() #this is how you combine data for all cond and types at once
calculateaimingangles() # this pulls out the aiming angles of each group and makes a csv file of them. 
```
```{r code for making figures}
svglite(file='Training Trials Across Conditions with Means.svg', width=5, height=15, system_fonts=list(sans = "Arial"))
layout(matrix(c(1,2,3,4,5), nrow=5, byrow=TRUE), heights=c(1,1,1,1,1))

  filenames <- c()
c <- 1
for (i in c(0,1,3,4,5)){
  filenames[c] <- sprintf("condition %d trialtype 1.csv", i)
  c <- c+1
}
conditions <- c(0,1,3,4,5)
b <- 1
for (file in filenames){
  plotdata(file, conditions[b], "Reaches", "mean")
  b <- b+1
}
  dev.off()
  
  
  
  svglite(file='No Cursor Trials Across Conditions with Medians.svg', width=5, height=15, system_fonts=list(sans = "Arial"))
layout(matrix(c(1,2,3,4), nrow=4, byrow=TRUE), heights=c(1,1,1,1))

  filenames <- c()
c <- 1
for (i in c(1,3,4,5)){
  filenames[c] <- sprintf("condition %d trialtype 0.csv", i)
  c <- c+1
}
conditions <- c(1,3,4,5)
b <- 1
for (file in filenames){
  plotdata(file, conditions[b], "No Cursor", "median")
  b <- b+1
}
  dev.off()
```
```{r codes for doing analysis}
reachrm <- PrepdataforANOVA(type = 1)
nocursorrm<- PrepdataforANOVA(type = 0, condition = c(1,3,4,5))
rmodel <- ANOVAanalysis(reachrm)
summary(rmodel)
ncmodel <- ANOVAanalysis(nocursorrm)
summary(ncmodel)
```




```{r SCAPPS figures}
svglite(file="figs/Poster Figures_1004a.svg", width=12, height=4, system_fonts=list(sans = "Arial"))
layout(matrix(1:2, nrow = 1, byrow = TRUE))
plotreachestogether()
plotnocursorstogether()
dev.off()

svglite(file="figs/Poster Figures_1004b.svg", width=12, height=8, system_fonts=list(sans = "Arial"))
layout(matrix(1:4, nrow = 2, byrow = TRUE))
plotaimingangles()
RegressionPLotEL()
RegressionPLotaiming()
dev.off()
plotSaturation()

```


```{r plots for CVR poster 2022}

svglite(file="figs/Poster Figures_0524.svg", width=12, height=16, system_fonts=list(sans = "Arial"))
layout(matrix(1:8, nrow = 4, byrow = TRUE))
plotreachestogether()
plotnocursorstogether()
PlotzoomedINreaches()
PlotzoomedINNocursors()
RegressionPLotEL()
RegressionPLotEC()
plotaimingangles()
dev.off()

```


```{r load data}
continuous_reaches<- Cleandata('forwardana/condition 1 trialtype 1_cuttoff0.3.csv')
continuous_reaches<-Baselinedata(continuous_reaches)
write.csv(continuous_reaches, "continuous_reaches.csv", quote=FALSE, row.names = FALSE)
terminal_reaches<- Cleandata("forwardana/condition 3 trialtype 1_cuttoff0.3.csv")
terminal_reaches<-Baselinedata(terminal_reaches)
write.csv(terminal_reaches, "terminal_reaches.csv", quote=FALSE, row.names = FALSE)
cursorJump_reaches<- Cleandata("forwardana/condition 4 trialtype 1_cuttoff0.3.csv")
cursorJump_reaches<-Baselinedata(cursorJump_reaches)
write.csv(cursorJump_reaches, "cursorjump_reaches.csv", quote=FALSE, row.names = FALSE)

continuous_nocursors<- Cleandata("forwardana/condition 1 trialtype 0_cuttoff0.3.csv")
continuous_nocursors<-Baselinedata(continuous_nocursors)
write.csv( continuous_nocursors, "continuous_nocursors.csv", quote=FALSE, row.names = FALSE)
terminal_nocursors<- Cleandata("forwardana/condition 3 trialtype 0_cuttoff0.3.csv")
terminal_nocursors<-Baselinedata(terminal_nocursors)
write.csv(terminal_nocursors, "terminal_nocursors.csv", quote=FALSE, row.names = FALSE)
cursorJump_nocursors<- Cleandata("forwardana/condition 4 trialtype 0_cuttoff0.3.csv")
cursorJump_reaches<-Baselinedata(cursorJump_reaches)
write.csv(cursorJump_nocursors, "cursorJump_nocursors.csv", quote=FALSE, row.names = FALSE)
```



```{r setting up analysis}

anovadata<- PrepdataforANOVA()

TtestData<- PrepdataforT()
```


```{r running analysis}
rmodel<- ANOVAanalysis(anovadata[anovadata$Task == "Reaches",])
rmodel
ncmodel<- ANOVAanalysis(anovadata[anovadata$Task == "No-Cursors",])
ncmodel

IndependentT(TtestData, "Continuous", "Terminal", "Reaches")
IndependentT(TtestData, "Continuous", "CursorJump", "Reaches")
IndependentT(TtestData, "Terminal", "CursorJump", "Reaches")

IndependentT(TtestData, "Continuous", "Terminal", "No-Cursors")
IndependentT(TtestData, "Continuous", "CursorJump", "No-Cursors")
IndependentT(TtestData, "Terminal", "CursorJump", "No-Cursors")

  

```
